# Generated by Django 5.1.1 on 2024-09-21 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="введите название поста",
                        max_length=50,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="slug"
                    ),
                ),
                ("context", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="загрузите изображение поста",
                        null=True,
                        upload_to="blog/",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime.now,
                        verbose_name="дата создания поста",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="опубликовано"),
                ),
                (
                    "views_counter",
                    models.PositiveIntegerField(default=0, verbose_name="просмотры"),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
                "ordering": ["title", "created_at", "views_counter"],
            },
        ),
    ]
