# Generated by Django 5.1.1 on 2024-09-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.BooleanField(unique=True),
        ),
    ]
