# Generated by Django 5.1 on 2024-09-04 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_remove_product_manufactured_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateField(
                default=datetime.datetime.now, verbose_name="дата редактирования"
            ),
        ),
    ]
